\\ Generate Magma QC script for fiber (m,n)
\\ Usage: MVAL=m NVAL=n gp -q gen_magma_script.gp > qc_m_n.magma

default(parisize, 4000000000);
default(realprecision, 38);

mm = eval(getenv("MVAL"));
nn = eval(getenv("NVAL"));

q0_num = 2 * mm * nn;
q0_den = mm^2 - nn^2;
g0 = gcd(q0_num, q0_den);
q0_num /= g0;
q0_den /= g0;
q0 = q0_num / q0_den;

\\ Pythagorean check: need 1 + q^2 = w^2
w2 = 1 + q0^2;
wn = 0; wd = 0;
if(issquare(numerator(w2)) && issquare(denominator(w2)), wn = sqrtint(numerator(w2)); wd = sqrtint(denominator(w2)));

\\ For V_q affine model: clear denominators by D = denom(q)
\\ V_q: c^2 + q^2 = e^2, c^2 + 1 = f^2, c^2 + 1 + q^2 = g^2
\\ Multiply by q_den^2 = D^2: setting C = q_den*c etc:
\\ C^2 + (2mn)^2 = E^2,  C^2 + (m^2-n^2)^2 = F^2,  C^2 + (m^2+n^2)^2 = G^2

a_val = q0_num;        \\ = 2 m n
b_val = q0_den;        \\ = m^2 - n^2
c_val = mm^2 + nn^2;   \\ Pythagorean hypotenuse

E_ef_coef = [0, -2*(1+q0^2), 0, (1-q0^2)^2, 0];
E_eg_coef = [0, -2*(1+2*q0^2), 0, 1, 0];
E_fg_coef = [0, -2*(2+q0^2), 0, q0^4, 0];
E_Hp_coef = [0, 2 + 2*q0^2, 0, 1 + 3*q0^2 + q0^4, q0^2 + q0^4];
E_Hm_coef = ellfromeqn('y^2 - 'x * ('x + q0^2) * ('x + 1) * ('x + 1 + q0^2));

E_ef = ellminimalmodel(ellinit(E_ef_coef));
E_eg = ellminimalmodel(ellinit(E_eg_coef));
E_fg = ellminimalmodel(ellinit(E_fg_coef));
E_Hp = ellminimalmodel(ellinit(E_Hp_coef));
E_Hm = ellminimalmodel(ellinit(E_Hm_coef));

factors = [E_ef, E_eg, E_fg, E_Hp, E_Hm];
names   = ["E_ef","E_eg","E_fg","E_Hp","E_Hm"];

conds = vector(5, i, ellglobalred(factors[i])[1]);
badprimes_all = [];
for(i=1,5, bp = factor(conds[i])[,1]~; badprimes_all = setunion(Set(badprimes_all), Set(bp)));

ranks_lo = vector(5);
ranks_hi = vector(5);
gens_per = vector(5, j, []);
total_lo = 0; total_hi = 0;
for(i=1,5, r = ellrank(factors[i], 1); ranks_lo[i] = r[1]; ranks_hi[i] = r[2]; gens_per[i] = r[4]; total_lo += r[1]; total_hi += r[2]);

deny = denominator(q0); denyfact = if(deny == 1, [], factor(deny)[,1]~);
forbidden = setunion(Set(badprimes_all), Set(denyfact));
forbidden = setunion(forbidden, Set([2]));
candidate_primes = [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113];
chosen_p = -1;
for(k=1,#candidate_primes, pp = candidate_primes[k]; if(setsearch(forbidden, pp) == 0 && chosen_p < 0, aps = vector(5, i, ellap(factors[i], pp)); ordinary = 1; for(i=1,5, if(aps[i] % pp == 0, ordinary = 0)); if(ordinary, chosen_p = pp)));

\\ Now emit Magma script
print("// Quadratic Chabauty Magma script for V_q at (m,n) = (", mm, ",", nn, ")");
print("// Generated by gen_magma_script.gp");
print("// q = ", q0_num, "/", q0_den);
print("//   1 + q^2 = ", wn, "^2 / ", wd, "^2");
print("// Total rank on J(V_q): [", total_lo, ",", total_hi, "]");
print("// Prime of good ordinary reduction: p = ", chosen_p);
print("// QC margin: g + rho_NS - 1 - r_hi = 5 + 5 - 1 - ", total_hi, " = ", 9 - total_hi);
print("");
print("// Required: Magma 2.27+ with QCMod (Balakrishnan-Best-Bianchi 2021)");
print("// Repo: https://github.com/jbalakrishnan/QCMod");
print("");
print("SetVerbose(\"QCMod\", 1);");
print("AttachSpec(\"QCMod/spec\");");
print("");
print("// === Curve V_q in P^3 (intersection of 3 quadrics) ===");
print("// With C = ", b_val, " c, E = ", b_val, " e, F = ", b_val, " f, G = ", b_val, " g:");
print("//   E^2 = C^2 + ", a_val^2);
print("//   F^2 = C^2 + ", b_val^2);
print("//   G^2 = C^2 + ", c_val^2);
print("P3<C, E, F, G> := ProjectiveSpace(Rationals(), 3);");
print("V := Curve(P3, [");
print("    E^2 - C^2 - ", a_val^2, ",");
print("    F^2 - C^2 - ", b_val^2, ",");
print("    G^2 - C^2 - ", c_val^2);
print("]);");
print("assert Genus(V) eq 5;");
print("");
print("// === Five elliptic factors of J(V_q) ===");
for(i=1,5, c = factors[i][1..5]; print(names[i], " := EllipticCurve([", c[1], ", ", c[2], ", ", c[3], ", ", c[4], ", ", c[5], "]);"); print("// rank in [", ranks_lo[i], ",", ranks_hi[i], "]; conductor ", conds[i]));
print("");
print("// === Mordell-Weil generators (from PARI ellrank, effort=1) ===");
print("gens_ef := [");
for(k=1,#gens_per[1], P = gens_per[1][k]; print("    E_ef![", P[1], ", ", P[2], "]", if(k<#gens_per[1], ",", "")));
print("];");
print("gens_eg := [");
for(k=1,#gens_per[2], P = gens_per[2][k]; print("    E_eg![", P[1], ", ", P[2], "]", if(k<#gens_per[2], ",", "")));
print("];");
print("gens_fg := [");
for(k=1,#gens_per[3], P = gens_per[3][k]; print("    E_fg![", P[1], ", ", P[2], "]", if(k<#gens_per[3], ",", "")));
print("];");
print("gens_Hp := [");
for(k=1,#gens_per[4], P = gens_per[4][k]; print("    E_Hp![", P[1], ", ", P[2], "]", if(k<#gens_per[4], ",", "")));
print("];");
print("gens_Hm := [");
for(k=1,#gens_per[5], P = gens_per[5][k]; print("    E_Hm![", P[1], ", ", P[2], "]", if(k<#gens_per[5], ",", "")));
print("];");
print("");
print("MW := [* < E_ef, gens_ef >, < E_eg, gens_eg >, < E_fg, gens_fg >, < E_Hp, gens_Hp >, < E_Hm, gens_Hm > *];");
print("");
print("// === Base point: a degenerate (c=0) point on V_q ===");
print("// c=0 gives (E, F, G) = (+- ", a_val, ", +- ", b_val, ", +- ", c_val, ")");
print("b_pt := V![0, ", a_val, ", ", b_val, ", ", c_val, "];");
print("");
print("// === Run QC ===");
print("p := ", chosen_p, ";");
print("N := 20;  // p-adic precision (increase to 25 for higher reliability; ~32GB RAM)");
print("");
print("// QCModAffine is the Balakrishnan-Best-Bianchi 2021 driver");
print("// candidates := QCModAffine(V, p, N : MWBasis := MW, BasePoint := b_pt);");
print("// Print all candidate points (V(Q_p) cap V(Q-bar))");
print("// printf \"QC candidates: %o\\n\", candidates;");
print("");
print("// Expected output for tractable cases (r_hi <= 8): finite set of size 8 (the c=0 degenerate points)");
print("// If output size > 8: requires further sieving or beyond-QC method");
print("");
print("quit;");

quit;
