/* Step 5: Mod-p Chabauty test for rank-1 case.
 *
 * Strategy:  for each good prime p, enumerate E_Hm(F_p),  identify the image of E_Hm(Q) -> E_Hm(F_p)
 * (which is generated by G_p and T_p mod p), and count points in that image with x ≠ 0 and -Q/x = square mod p.
 *
 * If ZERO such points exist for any good prime p, then no Q ∈ E_Hm(Q) maps to a non-branch H-point.
 *
 * We don't need G — we just need the SUBGROUP generated by G_p (= a cyclic group of some order dividing #E(F_p)/#torsion).
 *
 * BETTER: at primes p such that  rk E_Hm(Q) = 1  and the reduction is good, the image of  E(Q)/E(Q)_tors  in  E(F_p)/T_p  is cyclic of order dividing  #E(F_p)/16  (16 = |T|).  If this quotient has order 1 for some p, then G ≡ T (mod p), and the whole image is the torsion image — which we already enumerated.
 *
 * Looking for primes where #E(F_p) = 16  (or its 2-part is exactly 16).
 */

m = 63; n = 38;
a = m^2 - n^2;   X2 = a^2;
b = 2*m*n;       X3 = b^2;
dab = m^2 + n^2; X1 = dab^2;
S = X1+X2+X3; P = X1*X2 + X1*X3 + X2*X3; Q = X1*X2*X3;
E = ellinit([0, P, 0, Q*S, Q^2]);
bad = [2, 3, 5, 7, 19, 31, 71, 73, 101, 103, 5413];

print("Looking for primes p where image of E(Q)/E(Q)_tors in E(F_p) is trivial...");
print("(equiv: |E(F_p)| / 16 has no large factor relatively prime to torsion order or it equals 1.)");
print();
print("p     |E(Fp)|    |E(Fp)|/16    ");
for(k=1, 60, \
  p = prime(k); \
  if(setsearch(Set(bad), p), next); \
  ap = ellap(E, p); \
  Np = p + 1 - ap; \
  print(p, "    ", Np, "    ", Np/16.0));
