/* ==========================================================================
   Test candidate Brauer-Manin obstructions at p = 2

   For a hypothetical perfect cuboid (a,b,c,d,e,f,g), evaluate candidate
   2-adic local invariants for various quaternion algebras (P,Q).

   We use the parity constraint: a odd, b,c even with v2(b) ne v2(c),
   min(v2(b),v2(c)) = 2.

   Strategy: enumerate (a,b,c) mod 2^k for some k, check each satisfies
   the face/space-diagonal equations mod 2^k, compute Hilbert symbols
   for various (P,Q), and tabulate.
   ========================================================================== */

\\ Generate 2-adic V-points modulo 2^K
\\ A "2-adic V-point mod 2^K" is (a,b,c,d,e,f,g) in (Z/2^K)^7 with:
\\   a^2+b^2 = d^2 mod 2^K
\\   b^2+c^2 = e^2 mod 2^K
\\   a^2+c^2 = f^2 mod 2^K
\\   a^2+b^2+c^2 = g^2 mod 2^K
\\ and a odd, b=c=0 mod 4 (parity constraint)

\\ For BM with quaternion classes, only the square classes mod 2 (or mod 8) matter.
\\ Actually quaternion (P,Q)_2 = (-1)^{f(P,Q)} where f is computed from
\\ valuations and units; precisely, depends on P,Q mod (Q_2^*)^2.
\\ The group Q_2^*/(Q_2^*)^2 has 8 elements, generated by 2, -1, 5.

\\ So we only need to know P, Q in Q_2^*/(Q_2^*)^2.

\\ A 2-adic V-point is a tuple in (Q_2)^7 with the equations.
\\ Its image in (Q_2^*/(Q_2^*)^2)^7 carries the BM info.

\\ Let's parametrize. Set v2(a) = 0, v2(b) = m (≥2), v2(c) = n (≥2) with say m=2, n>=4.
\\ Write a = a' (odd unit), b = 2^m b', c = 2^n c' (b',c' odd units).
\\ Then a^2 + b^2 = a^2 (1 + 4^m b'^2/a^2) — for m=2, this is a^2 + 16 b'^2.
\\ d^2 = a^2 + 16 b'^2 — d is odd. Modulo 8: a^2 mod 8 = 1, so d^2 = 1 + 16 b'^2 mod 8 = 1.

\\ Let's just enumerate small primitives.

print("=== Enumeration of small (a,b,c) mod 2^K satisfying ALL FOUR equations ===");
\\ For K = 5 (= mod 32), find solutions
K = 6;  \\ work mod 64
M = 2^K;

\\ Brute force (a,b,c) all (mod M) with a odd, 4|b, 4|c.
\\ For each, find d,e,f,g such that d^2 = a^2+b^2, etc.

count = 0;
solutions = List();
{
  for(a=1, M-1, if(a%2==1,
    for(b=0, M-1, if(b%4==0,
      my(d2 = (a^2+b^2) % M, d);
      \\ Find d with d^2 ≡ d2 mod M
      d = -1;
      for(dt=1, M-1, if((dt^2 - d2) % M == 0, d = dt; break));
      if(d >= 0,
        for(c=0, M-1, if(c%4==0,
          my(e2 = (b^2+c^2)%M, f2 = (a^2+c^2)%M, g2 = (a^2+b^2+c^2)%M);
          if(issquare(Mod(e2,M)) && issquare(Mod(f2,M)) && issquare(Mod(g2,M)),
            count = count + 1;
            if(#solutions < 5, listput(solutions, [a,b,c]))
          )
        ))
      )
    ))
  ));
}
print("Number of solutions mod ",M,": ", count);
print("First few: ");
for(i=1, #solutions, print(solutions[i]));
