import sympy as sp
u,v,w,p,q = sp.symbols('u v w p q', positive=True)

print("=== Saunderson parametrization: what does it cover? ===")
print()
print("Saunderson (1954) parametrizes PRIMITIVE EULER BRICKS (3 integer edges +")
print("3 integer FACE diagonals) by a primitive Pythagorean triple (u,v,w), u^2+v^2=w^2:")
print("   a = u(4v^2-w^2), b = v(4u^2-w^2), c = 4uvw")
print()
# Verify the three face-diagonal conditions are automatically integers:
a = u*(4*v**2-w**2); b = v*(4*u**2-w**2); c = 4*u*v*w
# face diagonals: sqrt(a^2+b^2), sqrt(b^2+c^2), sqrt(a^2+c^2)
for (X,Y,nm) in [(a,b,'a^2+b^2'),(b,c,'b^2+c^2'),(a,c,'a^2+c^2')]:
    S = sp.expand(X**2+Y**2)
    Sred = S.subs(w**2, u**2+v**2)
    for power in [8,6,4,2]:
        Sred = sp.expand(Sred.subs(w**power,(u**2+v**2)**(power//2)))
    print(f"  {nm} = {sp.factor(Sred)}  -> perfect square? {sp.sqrt(sp.factor(Sred))}")
print()
print("KEY QUESTION: does EVERY primitive Euler brick arise from Saunderson's (u,v,w)?")
print("  Saunderson's theorem: YES, every primitive Euler brick is parametrized this way")
print("  (this is a classical complete parametrization of the 3-face-diagonal condition).")
print()
print("Then PCP = Euler brick + integer SPACE diagonal g, g^2=a^2+b^2+c^2.")
print("We derived a^2+b^2+c^2 = w^2(w^4+16u^2v^2), and with (u,v,w)=(p^2-q^2,2pq,p^2+q^2),")
print("t=p/q:  (g/(w q^4))^2 = t^8+68t^6-122t^4+68t^2+1 = f(t).")
print()
print("=== THE COVERAGE GAP ===")
print("Two parametrization layers stacked:")
print(" (L1) Euler brick (u,v,w) primitive Pythagorean -> Saunderson: COMPLETE (every brick).")
print(" (L2) (u,v,w) Pythagorean parametrized by (p,q): u=p^2-q^2,v=2pq,w=p^2+q^2.")
print("      This is the COMPLETE parametrization of primitive Pythagorean triples")
print("      (p>q>0, gcd=1, opposite parity) -- so EVERY primitive (u,v,w) is hit.")
print()
print("=> The variable t=p/q ranges over ALL primitive Pythagorean (u,v,w),")
print("   and (t,T) in C'(Q) <-> PCP with space diagonal.  C' covers ALL PCPs in")
print("   Saunderson form -- this is the FULL cover, NOT a u*=square sub-cover!")
print()
print("=== Where does 'u*=t^2 square sub-cover' come from? ===")
print("E_PCP : T^2 = u*^4+68u*^3-122u*^2+68u*+1 with u* = t^2.")
print("C' -> E_PCP is the degree-2 cover t |-> u*=t^2.  A point on E_PCP gives a PCP")
print("only if its u*-coordinate is a rational SQUARE (so that t=sqrt(u*) in Q).")
print("So E_PCP(Q) is the QUOTIENT; the sub-cover language ('square-u*') describes")
print("E_PCP -> PCP, NOT C' -> PCP.  C' itself is the full cover.")
