print("=== Two distinct routes — which strata do they touch? ===")
print()
print("ROUTE A (per-fiber elliptic-Chabauty / Silverman, the EXCEPTIONAL-SET-CLOSURE doc):")
print("  Family E_PCP(q): y^2=x(x+1)(x+q^2), q=a/b parametrized by the Pythagorean-type")
print("  data; the rank-jump locus R={w=-1} stratified by sigma into the Z[sqrt2]-norm-form")
print("  square loci F5=d k^2, F6=d k^2 (d squarefree) + 2-adic v2(b) layers.")
print("  Closure is FIBER BY FIBER: each fiber is a rank-<=1 elliptic curve, Silverman/")
print("  Ingram-Mahe primitive-divisor kills Face-3 squares.  INFINITELY MANY curves")
print("  (one E_PCP per q), each needs its own (finite) N0.  d>1/F5/2-adic = the strata of")
print("  this infinite family.  Per-stratum uniform structure (tor=8, rank-1-in-R) verified,")
print("  but NO single uniform N0 over the infinite family.")
print()
print("ROUTE B (the genus-3 Coleman cover, THIS document):")
print("  ONE fixed curve C': T^2=f(t), t=p/q (Pythagorean parameter of the EULER BRICK).")
print("  C'(Q) <-> ALL PCPs in Saunderson form (full cover, all bricks, all d, all sigma).")
print("  rank J(C')=2 < genus 3 => Coleman gives |C'(Q)| <= 12 in ONE shot, UNCONDITIONAL,")
print("  SIGMA-FREE, and INDEPENDENT of the d/F5/2-adic stratification entirely.")
print()
print("=== The relationship between the two parametrizations ===")
print("Route A's q (the E_PCP modulus, = (m^2-n^2)/(2mn) type) and Route B's t=p/q")
print("(the Euler-brick Pythagorean ratio) are DIFFERENT variables on DIFFERENT moduli.")
print("Route B does not stratify by d at all: the single curve C' subsumes every d,")
print("every F5/F6 value, every 2-adic layer, because the Szpiro ratio sigma never enters.")
print()
print("=== So for step 4 the honest answer is: ===")
print("Route B (genus-3) does NOT need to 'extend' to d>1/F5/2-adic with more curves --")
print("it already covers them ALL with the SINGLE curve C'.  The d-stratification is a")
print("Route-A artifact.  C' is uniform across all of it by construction.")
print()
print("=== The genuine residual gap of Route B (honest) ===")
print("Coleman gives |C'(Q)| <= 12 but proves only FINITENESS+BOUND, not that the 8 known")
print("points are ALL of C'(Q).  Closing 12 -> 8 (ruling out up to 4 hypothetical extra")
print("points, which COULD be non-degenerate PCPs) needs Coleman p-adic integration to")
print("PIN the points = MAGMA (Coleman/QCMod).  PARI gives the bound, not the pinning.")
