\\ Check determinantal structure
\\
\\ Test: are the 4 quadrics expressible as 2x2 minors of some matrix?
\\
\\ For 2x2 minors of an m x n matrix of linear forms, the # minors is C(m,2)*C(n,2).
\\ We need 4 minors. So C(m,2)*C(n,2) = 4. Options:
\\   m=2, n=4: 1 * 6 = 6 (too many)
\\   m=2, n=3: 1 * 3 = 3 (too few)
\\   m=3, n=3: 3 * 3 = 9 (too many)
\\
\\ So strict determinantal isn't direct. But the variety could still be cut out
\\ by 4 selected minors of a 3x3 matrix (sub-Pfaffian etc.).
\\
\\ Alternative: 2x2 minors of a 2x4 matrix.
\\ A 2x4 matrix L has 6 minors. They define a determinantal variety of
\\ codim ≤ 3 generically. Codim < 4. So our V (codim 4) can't be cut out by
\\ ALL 2x2 minors of a 2x4 matrix.
\\
\\ However, since V is a complete intersection, by structure theorem for CI's:
\\ V is NOT determinantal in the strict sense. The Koszul complex IS its
\\ minimal free resolution.
\\
\\ Specifically: V Cohen-Macaulay (yes, CI is CM) of codim 4. Pfaffian / Eagon-
\\ Northcott would give codim ≤ 3 or specific values. CI of codim 4 has
\\ projective dimension 4, but determinantal cuts out codim 3 generically.

\\ Conclusion: V is a complete intersection, NOT determinantal.
\\ The Koszul resolution is THE minimal free resolution. Eagon-Northcott not applicable.

\\ Now compute cohomology dimensions h^i(O_V(k)) via Koszul / Serre duality.

\\ V is a smooth-or-singular complete intersection of 4 quadrics in P^6, dim 2.
\\ K_V = O_V(8 - 7) = O_V(1) by adjunction (K_V = O_V(sum d_i - n - 1) for CI in P^n,
\\ here n=6, sum d_i = 8, so K_V = O_V(8 - 7) = O_V(1).)
\\
\\ This makes V a surface with K_V ample (canonically embedded if V is smooth).
\\ V is a "general type" surface (when smooth).

\\ K^2 = c_1(K_V)^2 = (O_V(1))^2 = degree(V) = 16.

\\ Hilbert polynomial: P(n) = 8 n^2 + ...
\\ Specifically for CI of 4 quadrics in P^6:
\\ chi(O_V(n)) = HF(R/I)(n) - (corrections for n large enough)
\\
\\ For Castelnuovo-Mumford regularity reg(R/I) = 4: HF = HP for n >= 3.
\\ chi(O_V(n)) = HF(n) for n >= reg(I) - 1 = 3?
\\ Hilbert poly: from HF = 1, 7, 24, 56, 104, 168, 248, ...
\\ Fitting deg-2 polynomial to last 3 values:
\\   168 = 8*25 + b*5 + c  -> b*5 + c = -32
\\   248 = 8*36 + b*6 + c  -> b*6 + c = -40
\\   diff: b = -8, c = 8
\\ So HP(n) = 8 n^2 - 8 n + 8 = 8(n^2 - n + 1). Check:
\\   HP(2) = 8*3 = 24 ✓
\\   HP(3) = 8*7 = 56 ✓
\\   HP(4) = 8*13 = 104 ✓
\\   HP(5) = 8*21 = 168 ✓
\\   HP(1) = 8*1 = 8, HF(1) = 7. So HF != HP at n=1.
\\   HP(0) = 8, HF(0) = 1. Different.
\\ So HF = HP for n >= 2.

print("Hilbert polynomial P(n) = 8 n^2 - 8 n + 8 = 8(n^2 - n + 1)");
print("HF = HP for n >= 2");
print("chi(O_V) = P(0) = 8");
print("p_g + q + 1 = chi = 8 (for surface)");
print("If V smooth: p_g = h^2(O_V) = h^0(K_V) = h^0(O_V(1)) = 7");
print("(since K_V = O_V(1) and 7 = dim H^0(P^6, O(1)) restricted)");

\\ Actually p_g = h^0(K_V) = h^0(O_V(1)).
\\ From exact sequence 0 -> I -> O_{P^6} -> O_V -> 0 twisted by O(1):
\\ 0 -> H^0(I(1)) -> H^0(O_{P^6}(1)) -> H^0(O_V(1)) -> H^1(I(1)) -> 0
\\ H^0(I(1)) = 0 (no linear forms in I), H^1(I(1)) = ?
\\ HF_{R/I}(1) = 7, dim H^0(O_V(1)) = HF(1) = 7 if regular.
\\ So p_g = 7.
\\ q = h^1(O_V). For CI of dim >= 2 in P^n with n>= 3, the irregularity q = 0.
\\   (By Lefschetz / Larsen.)
\\ So chi = 1 - q + p_g = 1 - 0 + 7 = 8. ✓
print("Irregularity q = 0 (Lefschetz for CI in P^n, n>=3)");
print("Geometric genus p_g = 7");

\\ Picard group of V:
\\ For smooth CI in P^n of dim >= 3, Pic = Z generated by hyperplane (Noether-Lefschetz).
\\ For dim 2: Noether-Lefschetz says GENERIC such V has Pic = Z, but our V is
\\ special (defined over Q with special quadrics).
\\
\\ The hyperplane sections of V from linear forms in P^6 give one class.
\\ Additional Picard classes arise from special structures (e.g., fibrations).
\\ Note V contains many lines!
\\ E.g., V ∩ {a=0, d=0, b=±d, ...}
\\ Trivial points on V: (0,0,0,*,...) etc.

\\ Compute # ℙ¹'s on V via specialization:
\\ Setting a = b: Q1 = 2a^2 - d^2, so d^2 = 2a^2 -- no Q-solution for d/a ≠ 0
\\ unless we go to extensions.
\\
\\ Setting a = 0: Q1: b^2 = d^2, Q2: b^2+c^2=e^2, Q3: c^2=f^2, Q4: b^2+c^2=g^2
\\ So d=±b, f=±c, e=±g, b^2+c^2=e^2.
\\ For each (b,c), if b^2+c^2 is a square e^2, then 8 sign choices.
\\ This is a CURVE on V (1-dim), specifically pairs (b,c,e) with b^2+c^2=e^2
\\ (a Pythagorean conic) times 8 sign choices.
\\
\\ Similarly setting any of a,b,c,d,e,f,g to zero gives a curve on V.
\\ These give MANY divisor classes, suggesting Pic(V) has rank > 1.

print("\nDegenerate curves on V:");
print("V ∩ {a=0}: Pythagorean conic (b^2+c^2=e^2) × sign choices");
print("V ∩ {b=0}, {c=0}: similar");
print("V ∩ {d=0}: a^2+b^2=0 (only over C, no real points except origin)");
print("These give effective divisor classes, suggesting rho(V) > 1");

\\ Bottom line: rho(V) >= 2 most likely, potentially higher.
\\ This means rational points may have nontrivial structure beyond hyperplane class.

quit;
