#!/usr/bin/env python3
"""
E_8 lattice analysis of the PCP 7-vector.

The Coxeter / Cayley integral octonions (octavians) form a maximal order
in O = Cayley octonions. Their additive lattice, equipped with the norm
form N(x) = x x-bar, is isomorphic to the E_8 root lattice (up to scaling
of norm by factor 2).

Standard E_8 root lattice convention (Bourbaki / OEIS conventions):
  E_8 = {x ∈ R^8 : all x_i in Z, or all x_i in Z + 1/2;
                  sum x_i even}.
  Inner product: standard Euclidean.
  Roots (norm-2 vectors): 240 in number. There are no norm-1 vectors.
  Minimal norm = 2.

Cayley integers: maximal order containing Z<e_1,..,e_7> as an index-2
sub-lattice. In standard form, the Cayley integers correspond to
'doubled' E_8: under N(x), squared lengths in Cayley integers are
INTEGERS (not requiring factor 2). The Cayley integer lattice itself,
under N, gives a lattice isometric to E_8 SCALED by sqrt(2), i.e. with
minimal norm 4 (or 2 if rescaled).

Our PCP vector (with 0 in real coord): x = (0, a, b, c, d, e, f, g) ∈ R^8.
- All coords are integers => x is in Z^8, definitely in E_8 (since sum
  parity will be checked).
- N(x) = a^2+b^2+c^2+d^2+e^2+f^2+g^2 = 4 g^2.
- So x is a vector of squared norm 4 g^2 in Z^8 ⊂ E_8.

Question: what cosets of E_8 / 2E_8 does the PCP vector populate?
         what is the Gram matrix of the PCP-derived sub-lattice?
"""

import numpy as np
from fractions import Fraction

# We work with vectors in R^8 with coords (x_0, x_1, ..., x_7),
# where x_0 = 0 (real part) and (x_1,...,x_7) = (a, b, c, d, e, f, g).

# Define the seven "structural" PCP-vectors associated to a brick:
# v_a = (0,1,0,0,0,0,0,0) "edge a"
# ... etc. They are the standard basis of imaginary octonions.

# The PCP equations are RANK-4 quadratic constraints on the
# squared coordinates. So we can construct vectors in R^8 whose
# norms encode these:

# Vector for "a^2 + b^2 - d^2 = 0":  v_ab_d = (0, a, b, 0, d*i, 0, 0, 0, 0)
# But that needs to be embedded so squared norm captures the eqn.

# Better: directly compute Gram matrix of the 4 (or 7) "natural"
# vectors generated by PCP from a single brick (use the Halcke
# Saunderson near-miss).

# Halcke 1719 (44, 117, 240, 125, 244, 267, sqrt(73225)~270.6):
a, b, c = 44, 117, 240
d2 = a**2 + b**2; e2 = b**2 + c**2; f2 = a**2 + c**2
d = int(np.sqrt(d2)); e = int(np.sqrt(e2)); f = int(np.sqrt(f2))
g2 = a**2 + b**2 + c**2
print(f"Halcke brick: a={a}, b={b}, c={c}, d={d}, e={e}, f={f}, g^2={g2}")
print(f"  sqrt(g^2) ~ {np.sqrt(g2):.6f}, integer? {int(np.sqrt(g2))**2 == g2}")

# Now build the PCP vector in R^8 (with x_0 = 0; perfect cuboid would have x_8 = g integer):
g_floor = int(np.sqrt(g2))   # not integer for Halcke
# For checking ALL E_8 embeddings, treat g symbolically.

# We construct several candidate sub-lattices of E_8 \otimes Q
# that the PCP problem distinguishes.

# (1) Pythagorean triple sub-lattices:
# Triple (a, b, d) with a^2+b^2=d^2 corresponds to a Gaussian integer
# a+bi in Z[i] of norm d^2. In R^8 / E_8 language:
# vector (a, b, d) lifts to (a,0,0,b,0,0,d,0) (just an example placement).

# Let's think more carefully:
# The 'face Pythagorean structure' has 3 triples sharing pairs:
# T_ab: a^2+b^2=d^2
# T_bc: b^2+c^2=e^2
# T_ac: a^2+c^2=f^2
# T_abc: a^2+b^2+c^2=g^2 (and 2g^2 = d^2+e^2+f^2)

# Define 4 vectors in R^4 (then embed in R^8):
# u_1 = (a, b, 0, -d), N(u_1) = 2(a^2+b^2) [wait, with the sign: a^2+b^2+0+d^2 = 2d^2]
# Hmm, sign doesn't matter for norm. So u_1 = (a, b, 0, d) has N=2d^2.

# More useful: place each triple as a NULL vector in a 4-dim Lorentzian
# style. But we're in positive definite, so let's just see Gram matrices.

# Define the 4 vectors in R^7 (imag octonions):
# Standard basis (e_1..e_7), and look at how PCP solutions decompose.

# Actually the route-W1 file says: 'pure imag octonion
# o = a e_1 + b e_2 + c e_3 + d e_4 + e e_5 + f e_6 + g e_7'
# N(o) = a^2+...+g^2. We have N(o) = 4 g^2.

# So o lies on a 6-sphere of radius 2g in R^7 ⊂ R^8 = O.
# The 6-sphere R^7 (imag) is the sphere on which G_2 acts.

# The 7 coords are constrained by 4 quadratic eqns, so PCP locus in
# the 6-sphere (after rescaling by g) is a 3-dim variety in the 6-sphere.

# E_8 embedding question (Track B from the prompt):
# We embed (a/g, b/g, c/g, d/g, e/g, f/g, 1) into Q^7 ⊂ E_8 ⊗ Q.
# Compute its norm: (a^2+b^2+c^2+d^2+e^2+f^2)/g^2 + 1
#                 = (g^2 + 2g^2)/g^2 + 1 = 3 + 1 = 4.

# So the normalized 7-vector has Q-norm 4 = (2)^2 in the standard
# Euclidean form on R^7.

# That's NOT a vector of E_8 (E_8 has integer or half-integer coords).
# Hmm, unless we choose denominator carefully.

# A primitive PCP solution (g, a, b, c, d, e, f) has gcd 1. By the
# parity argument (two-even-one-odd: e.g., a, b even, c odd),
# d = sqrt(a^2+b^2) where a^2+b^2 is divisible by 4 (even + even),
# so d is even. e = sqrt(b^2+c^2) odd^2 + even^2 = odd, so e is odd.
# Similarly f odd. g^2 = sum, so even+even+odd = odd; g odd.

# So in primitive case: (a,b,c,d,e,f,g) = (even,even,odd,even,odd,odd,odd).
# Sum mod 2 = (0+0+1+0+1+1+1) = 4 = 0 mod 2. Good.

# Sum mod 2 of all 8 coords (including the 0 real part):
# 0 + (0+0+1+0+1+1+1) = 0 mod 2.   GOOD.

# So x = (0, a, b, c, d, e, f, g) is in the integer lattice Z^8 AND
# has even coordinate sum, so it IS an E_8 vector (since E_8 = D_8 ∪ (D_8 + (1/2)^8) ).
# In fact D_8 itself = {x in Z^8 : sum x_i even}. So our PCP vector is
# in D_8 ⊂ E_8. (E_8 = D_8 + Z·glue, where glue = (1/2)^8.)

# Squared E_8-norm of this vector = sum of squares = 4 g^2.

# QUESTION (a): What sub-lattices of E_8 contain ALL PCP vectors with
# a given primitive structure?  Is there a constraint mod 2E_8?

# Construct Gram matrix of 4 'natural' vectors derived from PCP:
# v1 = (0,a,b,c,d,e,f,g)            # the brick vector
# v2 = (0,b,c,a,e,f,d,g)            # cyclic permutation S_3 action
# v3 = (0,c,a,b,f,d,e,g)            # cyclic S_3
# v4 = (0,a,b,c,-d,-e,-f,g)        # 'antiparallel face diagonals'

# Use sympy for symbolic / exact computation
import itertools

def vec(coords):
    return np.array(coords, dtype=int)

# Halcke (a=44,b=117,c=240; not a PCP, just an Euler brick)
v1 = vec((0, a, b, c, d, e, f, 0))  # ignore g since it's not integer
print(f"\nHalcke (non-PCP): v1 = {v1}")
print(f"  N(v1) = {(v1*v1).sum()} = expected {(a*a+b*b+c*c+d*d+e*e+f*f)}")

# Now construct a HYPOTHETICAL PCP and compute Gram matrix:
print("\n--- Hypothetical PCP analysis ---")
print("Pretend (a,b,c,d,e,f,g) = (a,b,c,d,e,f,g) and compute Gram matrices symbolically.")

# We use symbolic via sympy:
from sympy import symbols, simplify, Matrix, sqrt, expand
sa, sb, sc, sd, se, sf, sg = symbols('a b c d e f g', positive=True)

# Constraint substitutions:
constraint_subs = {
    sd**2: sa**2 + sb**2,
    se**2: sb**2 + sc**2,
    sf**2: sa**2 + sc**2,
    sg**2: sa**2 + sb**2 + sc**2,
}

# Brick vector v0 in R^8 with x_0=0:
v0 = Matrix([0, sa, sb, sc, sd, se, sf, sg])
N0 = (v0.T @ v0)[0]
print(f"N(v0) = a^2+b^2+c^2+d^2+e^2+f^2+g^2")
N0_reduced = N0.subs(constraint_subs)
print(f"     = {expand(N0_reduced)} = 4 g^2 (under constraints)")

# Octonion conjugate: x-bar = -x for pure imaginary, so x x-bar = N(x).
# Now consider some 'derived' vectors:

# w1 = v0 (the brick itself)
# w2 = (0, -a, -b, -c, d, e, f, g) (negate edges)
# w3 = (0, a, b, c, -d, -e, -f, g) (negate face diagonals)
# w4 = (0, a, b, c, d, e, f, -g)  (negate space diagonal)
# These are all candidate E_8 vectors of squared norm 4g^2.

w1 = Matrix([0, sa, sb, sc, sd, se, sf, sg])
w2 = Matrix([0, -sa, -sb, -sc, sd, se, sf, sg])
w3 = Matrix([0, sa, sb, sc, -sd, -se, -sf, sg])
w4 = Matrix([0, sa, sb, sc, sd, se, sf, -sg])

vectors = [w1, w2, w3, w4]
n = len(vectors)
gram = Matrix.zeros(n, n)
for i in range(n):
    for j in range(n):
        ip = (vectors[i].T @ vectors[j])[0]
        gram[i, j] = expand(ip.subs(constraint_subs))

print("\nGram matrix of (w1, w2, w3, w4) under PCP constraints:")
for i in range(n):
    row = []
    for j in range(n):
        row.append(str(gram[i,j]))
    print("  [" + ", ".join(row) + "]")

print("\nDiagonal entries (norms):")
for i in range(n):
    print(f"  N(w_{i+1}) = {gram[i,i]}")
print(f"\nDeterminant of Gram:")
print(f"  det = {expand(gram.det())}")
