#!/usr/bin/env python3
"""
Octavian (Cayley integer) lattice analysis.

The maximal order of Cayley integers (octavians) in O is, in standard
form, the lattice with basis:
    e_0 = 1
    e_1, e_2, e_3, e_4, e_5, e_6, e_7
together with the 8 "half-integer" elements
    h_0 = (1+e_1+e_2+e_4)/2 + (e_3+e_5+e_6+e_7)/2*0 ...
The standard presentation uses Coxeter's choice with the 'integral cells'.

Concretely (Conway-Smith 'On Quaternions and Octonions', Ch. 9):
The octavians form a lattice isomorphic to E_8 (scaled by sqrt(1/2)
relative to the standard E_8 root lattice — i.e., the minimal norm
of a non-zero octavian is 1, and the lattice has covolume 1/16
which is non-unimodular by a factor of sqrt(2)).

For our PCP analysis, the key question is:
DOES THE PCP VECTOR x = a e_1 + b e_2 + c e_3 + d e_4 + e e_5 + f e_6 + g e_7
LIE IN THE INTEGER LATTICE Z<e_1,...,e_7> OR IN THE OCTAVIAN MAXIMAL ORDER?

Answer: x with integer components a, b, ..., g obviously lies in the
sub-lattice Z<e_1,...,e_7>. The question is whether the OCTAVIAN
factorization theory gives more information than the Lipschitz quaternion
analysis.

Conway-Smith Theorem: Octavians satisfy a NON-ASSOCIATIVE unique
factorization theorem - but FACTORIZATION IS PATH-DEPENDENT (depends on
choice of bracketing).

So the octavian factorization of x.x_bar = N(x) = 4 g^2 may have
RICH STRUCTURE, but extracting an obstruction requires more than just
the norm.

Let's compute concretely:
"""

import numpy as np
from sympy import symbols, simplify, Matrix, expand, factor, sqrt

# Define octonion multiplication via the Cayley-Dickson construction:
# Use Fano plane convention from Baez (2002).
# Multiplication table (Baez convention):
#   e_1 e_2 = e_3, e_2 e_3 = e_1, e_3 e_1 = e_2  (i,j,k quaternion)
#   e_1 e_4 = e_5, e_2 e_4 = e_6, e_3 e_4 = e_7
#   e_5 e_6 = e_7? Let me use Cayley-Dickson directly.

# Cayley-Dickson on quaternions H: O = H + l*H where (a + l*b)(c + l*d) =
#   (ac - d_bar b) + l (b c_bar + d a)
# This determines multiplication uniquely.

# Basis: e_0=1, e_1=i, e_2=j, e_3=k=i*j, e_4=l, e_5=l*i, e_6=l*j, e_7=l*k.

# Quaternion multiplication in H (Hamilton): i*j = k, j*k = i, k*i = j.
# e_1*e_2 = e_3
# e_2*e_3 = e_1
# e_3*e_1 = e_2

# Now Cayley-Dickson with l = e_4:
# (a + l b)(c + l d) = (a c - d_bar b) + l(b c_bar + d a)
# where bar is quaternion conjugation: 1_bar=1, i_bar=-i, etc.

# e_4 * e_1 = l * (i + 0) = l*i = e_5
# e_4 * e_2 = l * j = e_6
# e_4 * e_3 = l * k = e_7
# e_1 * e_4 = i * l = ? : (i + l*0)(0 + l*1) = (i*0 - 1_bar*0) + l(0*0_bar + 1*i) = l*i = e_5
# Wait that gives e_1 * e_4 = e_5 as well, but the formula:
#   (a + lb)(c + ld) with a=i, b=0, c=0, d=1:
#     real part: i*0 - 1_bar * 0 = 0  (d_bar = 1_bar = 1, b=0 so this is 0)
#     l part: 0 * c_bar + 1 * i = i
#   So e_1 e_4 = l*i = e_5.
# But octonion are NOT commutative, so we need to check e_4 e_1 carefully:
# e_4 * e_1 = (0 + l*1)(i + l*0) = (0*i - 0_bar*1) + l(1*i_bar + 0*0) = 0 + l*(-i) = -l*i = -e_5
# So e_4 e_1 = -e_5, e_1 e_4 = +e_5.

# So octonions ARE non-commutative. Let me build the full multiplication table.

# Multiplication table for octonions (e_i e_j) for i, j in {1..7}.
# Use the rule: e_i e_j = +/- e_k where (i, j, k) is one of the 7 'lines' in Fano plane.
# Generated by the basic ones (i,j,k as quaternions) plus:
#   e_4 e_1 = -e_5, e_4 e_2 = -e_6, e_4 e_3 = -e_7 (from CD with l=e_4)
#   e_1 e_4 = e_5, e_2 e_4 = e_6, e_3 e_4 = e_7

# Let me compute systematically via CD:
def conj_quat(q):
    """Quaternion conjugate, q is tuple (w,x,y,z)"""
    return (q[0], -q[1], -q[2], -q[3])

def mul_quat(p, q):
    """Hamilton quaternion multiplication"""
    (a, b, c, d) = p
    (e, f, g, h) = q
    return (
        a*e - b*f - c*g - d*h,
        a*f + b*e + c*h - d*g,
        a*g - b*h + c*e + d*f,
        a*h + b*g - c*f + d*e,
    )

def mul_oct(p, q):
    """Octonion multiplication via Cayley-Dickson.
    p, q are tuples of 8 numbers (e_0, ..., e_7).
    Split as p = (a, b) where a, b are quaternions (4-tuples).
    """
    (a0, a1, a2, a3, b0, b1, b2, b3) = p
    (c0, c1, c2, c3, d0, d1, d2, d3) = q
    a = (a0, a1, a2, a3)
    b = (b0, b1, b2, b3)
    c = (c0, c1, c2, c3)
    d = (d0, d1, d2, d3)

    a_c = mul_quat(a, c)
    d_bar = conj_quat(d)
    db_b = mul_quat(d_bar, b)

    b_c_bar = mul_quat(b, conj_quat(c))
    d_a = mul_quat(d, a)

    real_part = tuple(a_c[i] - db_b[i] for i in range(4))
    imag_part = tuple(b_c_bar[i] + d_a[i] for i in range(4))

    return real_part + imag_part

def conj_oct(p):
    """Octonion conjugate: (a, b)^bar = (a_bar, -b)"""
    return (p[0], -p[1], -p[2], -p[3], -p[4], -p[5], -p[6], -p[7])

def norm_oct(p):
    """N(p) = p * p_bar. Returns the real part (norm)."""
    p_bar = conj_oct(p)
    r = mul_oct(p, p_bar)
    # Result should be (N(p), 0, ..., 0)
    return r[0]

# Verify multiplication table
e = [None]*8
for i in range(8):
    v = [0]*8
    v[i] = 1
    e[i] = tuple(v)

print("Octonion multiplication table (e_i e_j for i,j in 1..7):")
print("     | " + "  ".join(f"e_{j}" for j in range(1,8)))
print("-" * 60)
for i in range(1, 8):
    row = []
    for j in range(1, 8):
        prod = mul_oct(e[i], e[j])
        # Find nonzero component
        nz = [(k, prod[k]) for k in range(8) if prod[k] != 0]
        if len(nz) == 0:
            row.append(" 0 ")
        elif len(nz) == 1:
            k, sign = nz[0]
            s = "+" if sign > 0 else "-"
            row.append(f"{s}e_{k}")
        else:
            row.append(f"???")
    print(f"e_{i}  | " + " ".join(row))

# Now verify N(o) for a PCP-style vector:
print("\n--- Norm computation for PCP-style octonion ---")
# Use Halcke brick (a, b, c) = (44, 117, 240); g^2 = 73225, g_floor = 270 (not integer)
a, b, c = 44, 117, 240
d2 = a**2 + b**2  # 125^2
e2 = b**2 + c**2  # 267^2
f2 = a**2 + c**2  # 244^2
dv = int(np.sqrt(d2))
ev = int(np.sqrt(e2))
fv = int(np.sqrt(f2))
g2 = a**2 + b**2 + c**2
# Use g = sqrt(g2) (irrational)
gv = float(np.sqrt(g2))

# Octonion x = a*e_1 + b*e_2 + c*e_3 + d*e_4 + e*e_5 + f*e_6 + g*e_7
# Components in (e_0, ..., e_7) = (0, a, b, c, d, e, f, g)
x = (0.0, a, b, c, dv, ev, fv, gv)
nx = norm_oct(x)
print(f"  N(x) for Halcke = {nx:.4f}")
print(f"  Expected 4*g^2 = {4*g2}")
print(f"  Match: {abs(nx - 4*g2) < 1e-6}")

# Now, the important question: what is x * x?  (Since x is purely imaginary,
# x_bar = -x, so x*x_bar = -x*x = N(x), hence x*x = -N(x).  But is that
# obviously true?)
xx = mul_oct(x, x)
print(f"\n  x * x = {[f'{v:.2f}' for v in xx]}")
print(f"  Expected: (-N(x), 0, ..., 0) = ({-nx:.2f}, 0, ..., 0)")
# Verify pure imaginary squared gives -|.|^2
# Indeed all 7 imaginary components should be 0.
imag_parts = xx[1:]
print(f"  Imag parts of x*x: {[f'{v:.6f}' for v in imag_parts]}")
print(f"  Max abs imag: {max(abs(v) for v in imag_parts):.6f}")

# This is the FUNDAMENTAL OCTONION IDENTITY for purely imaginary x:
# x^2 = -N(x) (a REAL SCALAR).  So PCP gives x^2 = -4g^2 in O.

# The Cayley algebra is alternative: x(xy) = (xx)y = -N(x) y.
# So for ANY y in O: x(xy) = -4 g^2 * y.

# What does this say about the lattice structure?
# x(xy) = -4 g^2 y means that 'multiplication by x' on the left,
# squared, is just scaling by -4 g^2.

# So L_x is an 8x8 real matrix with L_x^2 = -4 g^2 I.
# Eigenvalues of L_x are ±2gi (pure imaginary).
# Det(L_x) = (2g)^8 = 256 g^8 (positive).

# This is just the standard 'multiplication by a pure imaginary norm-N(x)
# octonion gives an operator squaring to -N(x)*I' fact. No new info for PCP.

# Try to find an integer structural condition:
# Octavian integrality requires more than rational integer coords.
# Specifically, the Cayley integers / octavians L_O:
#   Coxeter's basis: e_0, e_1, ..., e_7 plus h = (e_0 + e_1 + e_2 + e_4) / 2  etc.
#   The lattice contains: integer linear combinations of (e_0, e_1, ..., e_7) AND half-integer combinations
#   where the half-integer pattern matches one of 16 specific 'quads'.
# Specifically: an element x = sum c_i e_i is octavian iff
#   (1) all c_i are integers, OR
#   (2) all c_i are half-integers in Z/2 + 1/2, AND the set of i with c_i odd
#       (in 2c_i) forms one of the 14 'quads' in the E_8 octad system.
# This is the E_8 lattice in 8D space.

# For PCP integer brick (a, b, ..., g all integers, plus 0 real part):
# Component c_0 = 0 (integer), c_1=a, ..., c_7=g all integers.
# So x lies in the standard integer sub-lattice Z<e_0,...,e_7>.
#
# Whether x is 'primitive in the octavian lattice' depends on additional gcd considerations.
# If gcd(a, b, c, d, e, f, g) = m, then x = m * y where y is also octavian and N(y) = N(x)/m^2.
#
# For a primitive PCP (gcd(a,b,c)=1), the octavian gcd of x might still be > 1 if some
# halving combinations work. Let me check.

# For Halcke (44, 117, 240, 125, 244, 267):  gcd = 1.
# x = 44 e_1 + 117 e_2 + 240 e_3 + 125 e_4 + 244 e_5 + 267 e_6 + 270.6.. e_7
# Components mod 2: 0 1 0 0 1 0 1 (g_floor=270 is even, but g is irrational).
# In an actual PCP, components mod 2 would be (0, even, even, odd, even, odd, odd, odd) (typical case).

# OCTAVIAN HALVING condition: x is 'twice an octavian' iff (x/2) is octavian.
# (x/2) is octavian iff EITHER all components of x are even, OR
# the set {i : x_i odd} is one of the 16 quad patterns (size 4 patterns).

# For primitive PCP with parity (0, 0, 0, 1, 0, 1, 1, 1) (where x_0=0, position 3=c odd, 5=e odd, 6=f odd, 7=g odd):
# odd-position set = {3, 5, 6, 7}. Is this a quad?

# The 14 quads in the E_8 / Coxeter setup form a Steiner system S(3, 4, 8).
# Conway-Smith specifies them as the complements (in {0..7}) of certain octads.
# In fact, the 14 + 1 = 15 sets of size 4 closed under multiplication ARE
# the 'tetrads' but the count is 14 even tetrads in the projective Fano plane PG(3, 2).
# Hmm, let me look up.

# E_8 / 2 E_8 ≅ F_2^8. The QUADRATIC FORM (N(x)/2 mod 2) has 135 + 120 = 255 nonzero classes.
# The isotropic ones are 135.
# Among weight-4 vectors in F_2^8, the isotropic weight-4 are exactly the 'tetrads' = 14 of them.

# Actually, in the standard E_8 coordinate system with the half-integer glue
# vector (1/2)^8, the half-integer points of E_8 are exactly:
#   { (x_1, ..., x_8) : all x_i in Z + 1/2, sum x_i in 2Z }
# Number of these of squared norm 2: 2^7 = 128 (= 'spinors').
# Total norm-2 vectors: 240 = 112 (integer) + 128 (half-integer).

# Our PCP vector has INTEGER coordinates. So it cannot be in the spinor part.
# It's in D_8 ⊂ E_8 (integer lattice with even coord sum).

# Quads / tetrads for HALVING:
# An integer vector v with sum 0 mod 2 (i.e. v in D_8) is in 2*D_8 iff
# all coords of v are even.
# So 'v in 2 E_8 iff v in 2 D_8 + 2 (half-integer glue)' = 'v has all coords in 2Z, or all in 2Z + 1'.

# For PCP integer-coord vector: v in 2*E_8 iff all components are even.
# Primitive PCP has (even, even, odd, even, odd, odd, odd) at imag positions
# plus 0 at real. So NOT in 2*E_8 (since c is odd).

# Half-integer 'tetrad' classification:
# In E_8 / 2E_8 ≅ F_2^8 (with even-weight constraint giving D_8/2D_8 ≅ F_2^7 ⊂ F_2^8):
# The integer vectors form a 128-element subspace (= D_8/2D_8 = even weight in F_2^8).
# Among these, the orbit structure under E_8 isometry group...

print("\n\n--- Octavian halving condition ---")
print("PCP primitive vector parity (typical case): (0, 0, 0, 1, 0, 1, 1, 1)")
print("Sum of parities = 4 (even, so in D_8 ⊂ E_8).")
print("All components NOT even (since c, e, f, g are odd), so NOT in 2*E_8.")
print("Hence (1/2) * x_PCP is NOT octavian — no halving.")
print("This means x_PCP is 'primitive' as an octavian, but this is")
print("the same statement as gcd(a,b,c,d,e,f,g) being odd. No new structure.")
