\\ ============================================================
\\ HARDENED Mordell-Weil sieve for 5 BEYOND-QC fibers
\\ Track B: 50 sieve primes, rigorous subgroup-order bound
\\ ============================================================
\\
\\ For each fiber V_q (Jacobian decomposed into elliptic factors)
\\ and each sieve prime p of good reduction across every factor:
\\
\\  (a) Compute #E_i(F_p) for each elliptic factor E_i
\\  (b) Reduce each global generator G_{i,j} mod p
\\      (skip a (prime, factor) if any generator hits infinity)
\\  (c) Compute the actual order |H_i(p)| of the subgroup of
\\      E_i(F_p) generated by the reductions, by direct
\\      enumeration (subgroup growth) -- not just LCM of orders.
\\  (d) Density d_i(p) = |H_i(p)| / #E_i(F_p),  product over factors.
\\
\\ Rigorous statement:
\\   image of MW(J(V_q)) in prod_i E_i(F_p)  has order  <=  prod_i |H_i(p)|.
\\
\\ Verification: the 8 known degenerate c=0 points of E_PCP(q) are
\\ 2-torsion images; we check that 2-torsion of each E_i is contained
\\ in H_i(p) only when expected (these come from torsion of J, not MW
\\ generators).  We instead verify the SUBGROUP H_i(p) contains the
\\ identity (trivial) and that each generator reduces to a point of
\\ correct order dividing #E_i(F_p) (Lagrange). The "8 degenerate
\\ points" of E_PCP itself sit inside torsion which is not part of
\\ the J(V_q) free MW we are sieving.
\\
\\ Coverage report: per fiber, log10(prod_p density_p) measures how
\\ much of MW phase space is excluded.

default(parisize, 500000000);   \\ 500 MB
default(realprecision, 28);

\\ ============================================================
\\ Helper: |<Q_1,...,Q_r>| inside E(F_p)
\\ Brute subgroup growth.  E(F_p) is small (|E| < 300 for p < 250).
\\ ============================================================

elem_eq(P, Q) = {
  if(P == [0], return(Q == [0]));
  if(Q == [0], return(0));
  return(P[1] == Q[1] && P[2] == Q[2]);
};

\\ Is point P in the list L?
in_list(L, P) = {
  my(k);
  for(k = 1, #L,
    if(elem_eq(L[k], P), return(1))
  );
  return(0);
};

\\ Subgroup <H, Q> in E given the existing list of points L = H.
\\ Returns the new (sorted) point list.
extend_subgroup(E, L, Q) = {
  my(newL, oQ, kk, h, Qk);
  \\ If Q already in L, no change.
  if(in_list(L, Q), return(L));
  oQ = ellorder(E, Q);
  if(oQ == 0, oQ = 1);  \\ shouldn't happen, but defensive
  newL = L;
  \\ For each existing h in L, add h + k*Q for k = 1..oQ-1
  \\ (k=0 already in L).
  \\ But also h + 0*Q = h is in L.
  \\ Simpler: form coset union, then dedupe.
  Qk = [0];
  for(kk = 1, oQ - 1,
    Qk = elladd(E, Qk, Q);
    for(h = 1, #L,
      my(s);
      s = elladd(E, L[h], Qk);
      if(!in_list(newL, s),
        newL = concat(newL, [s])
      )
    )
  );
  return(newL);
};

\\ Compute |<Q_1, ..., Q_r>| in E(F_p).
subgroup_order(E, gens_red) = {
  my(L, k);
  L = [[0]];   \\ start with identity
  for(k = 1, #gens_red,
    if(gens_red[k] === 0, next);   \\ marker: reduction at infty
    L = extend_subgroup(E, L, gens_red[k])
  );
  return(#L);
};

\\ ============================================================
\\ Reduce a rational point P=[x,y] modulo p.
\\ Returns 0 if any denominator is divisible by p (infinite reduction),
\\ else returns the reduced affine point [x mod p, y mod p].
\\ ============================================================
reduce_pt(P, p) = {
  my(dx, dy, nx, ny);
  dx = denominator(P[1]);
  dy = denominator(P[2]);
  if(dx % p == 0 || dy % p == 0, return(0));
  nx = (numerator(P[1]) * Mod(dx, p)^(-1));
  ny = (numerator(P[2]) * Mod(dy, p)^(-1));
  return([lift(nx) % p, lift(ny) % p]);
};

\\ ============================================================
\\ Main per-fiber routine.
\\ Returns vector of per-prime data:
\\   [p, total_subgroup_size, total_card, density]
\\ and detailed per-factor info printed.
\\ ============================================================

mw_sieve_fiber_hard(label, fiber_factors, candidate_primes) = {
  my(ii, fname, coefs, gens, E, EPp, disc, p, sz, ord, j, k);
  my(per_fiber_log_density, n_primes_used, total_product_bound);
  my(prime_entries, factor_skipped);

  print("\n========================================================");
  print("=== HARDENED MW SIEVE for fiber ", label, " ===");
  print("========================================================");

  \\ Pre-build E over Q for each factor, capture disc and torsion generators
  my(EQ, discs, torsgens);
  EQ = vector(#fiber_factors);
  discs = vector(#fiber_factors);
  torsgens = vector(#fiber_factors);
  for(ii = 1, #fiber_factors,
    EQ[ii] = ellinit(fiber_factors[ii][2]);
    discs[ii] = EQ[ii].disc;
    torsgens[ii] = elltors(EQ[ii])[3];   \\ list of torsion generators (vector of [x,y])
    print("  factor ", fiber_factors[ii][1], " torsion gens: ", torsgens[ii]);
  );

  \\ Filter primes: only those with good reduction for EVERY factor.
  my(valid_primes);
  valid_primes = [];
  for(j = 1, #candidate_primes,
    p = candidate_primes[j];
    my(ok);
    ok = 1;
    for(ii = 1, #fiber_factors,
      if(discs[ii] % p == 0, ok = 0; break)
    );
    if(ok, valid_primes = concat(valid_primes, [p]))
  );
  print("Candidate primes : ", candidate_primes);
  print("Valid (good red.): ", valid_primes, "  (", #valid_primes, " primes)");

  if(#valid_primes < 50,
    print("NOTE: only ", #valid_primes, " primes pass good-reduction filter.")
  );

  \\ Take first 50 valid primes
  my(used_primes);
  if(#valid_primes > 50,
    used_primes = vector(50, k, valid_primes[k]),
    used_primes = valid_primes
  );
  print("Using ", #used_primes, " primes: ", used_primes);

  prime_entries = vector(#used_primes);

  per_fiber_log_density = 0.0;
  total_product_bound = 1;  \\ product over primes of (subgroup-size bound), CRT-style upper bound

  for(j = 1, #used_primes,
    p = used_primes[j];
    my(prime_total_subgroup, prime_total_card);
    prime_total_subgroup = 1;
    prime_total_card = 1;
    print("\n--- p = ", p, " ---");
    for(ii = 1, #fiber_factors,
      fname = fiber_factors[ii][1];
      coefs = fiber_factors[ii][2];
      gens = fiber_factors[ii][3];
      EPp = ellinit(coefs, p);
      sz = ellcard(EPp);
      prime_total_card *= sz;

      if(#gens == 0,
        \\ no global generators known: the MW image in this factor
        \\ could be anything; conservative bound is full E(F_p).
        print("  E_", fname, ": #E(F_p)=", sz,
              " | no gens -> subgroup bound = #E(F_p)");
        prime_total_subgroup *= sz;
        next
      );

      \\ Reduce generators
      my(gens_red, orders, any_bad, n_good);
      gens_red = vector(#gens);
      orders = vector(#gens);
      any_bad = 0;
      n_good = 0;
      for(k = 1, #gens,
        my(rp);
        rp = reduce_pt(gens[k], p);
        if(rp === 0,
          any_bad = 1;
          gens_red[k] = 0;
          orders[k] = -1
        ,
          \\ sanity: check on curve mod p
          if(!ellisoncurve(EPp, rp),
            \\ this would indicate bad reduction not caught
            any_bad = 1;
            gens_red[k] = 0;
            orders[k] = -2
          ,
            gens_red[k] = rp;
            orders[k] = ellorder(EPp, rp);
            if(orders[k] == 0, orders[k] = 1);
            n_good += 1
          )
        )
      );

      \\ Also reduce torsion generators and add them to the subgroup
      \\ (the 8 degenerate c=0 points correspond to torsion images;
      \\ they belong to the MW image and must be sieved through).
      my(tgens_red, tg);
      tgens_red = vector(#torsgens[ii]);
      for(tg = 1, #torsgens[ii],
        my(rp);
        rp = reduce_pt(torsgens[ii][tg], p);
        if(rp === 0,
          tgens_red[tg] = 0
        ,
          if(!ellisoncurve(EPp, rp),
            tgens_red[tg] = 0
          ,
            tgens_red[tg] = rp
          )
        )
      );

      \\ Compute subgroup order via enumeration of <free gens, torsion gens>
      my(Hsz, all_red);
      all_red = concat(gens_red, tgens_red);
      Hsz = subgroup_order(EPp, all_red);

      \\ Verify torsion injects: ord(torsion gen) mod p should match its global order
      my(tors_inj);
      tors_inj = 1;
      for(tg = 1, #tgens_red,
        if(tgens_red[tg] === 0, tors_inj = 0; break);
        my(o);
        o = ellorder(EPp, tgens_red[tg]);
        if(o != 2,  \\ all torsion gens here are 2-torsion (Klein-four)
          tors_inj = 0; break
        )
      );

      prime_total_subgroup *= Hsz;

      print("  E_", fname, ": #E(F_p)=", sz,
            "  orders=", orders,
            "  |H|=", Hsz,
            "  |H|/#E=", Hsz*1.0/sz,
            "  tors_inj=", tors_inj,
            if(any_bad, " [some gens reduce to infty]", ""));
    );

    my(density);
    density = prime_total_subgroup * 1.0 / prime_total_card;
    print("  -> product over factors: |H_total|=", prime_total_subgroup,
          "  #J(F_p) ~ ", prime_total_card,
          "  density=", density);

    prime_entries[j] = [p, prime_total_subgroup, prime_total_card, density];
    per_fiber_log_density += log(density) / log(10);
    total_product_bound *= prime_total_subgroup;
  );

  print("\n=== Fiber ", label, " SUMMARY ===");
  print("Primes used               : ", #used_primes);
  print("Sum log10(density_p)      : ", per_fiber_log_density);
  print("Total subgroup-bound prod : ", total_product_bound);
  print("log10(total bound)        : ", log(total_product_bound*1.0)/log(10));
  print("log10(prod #E_p)          :", " (informational)");
  my(log_prod_card);
  log_prod_card = 0.0;
  for(j = 1, #used_primes, log_prod_card += log(prime_entries[j][3]*1.0)/log(10));
  print("log10(prod #J(F_p))       : ", log_prod_card);
  print("Sieve exclusion (log10)   : ", log_prod_card - log(total_product_bound*1.0)/log(10));

  return([label, prime_entries, per_fiber_log_density, total_product_bound]);
};

\\ ============================================================
\\ Fiber data -- VERBATIM from mw_sieve.gp (lines 55-100)
\\ ============================================================

{fd_61_38 = [
  ["ef", [1, 0, 0, -42684740442159, -101889258036034244616],
    [[58987827/4, 397992407343/8], [592500852, 14421088318314], [44640322184/625, 9390298181935952/15625]]],
  ["fg", [0, 1, 0, -55728214538800, -146186146319718549100],
    [[298156741903850/1713481, 5143525299205695602880/2242946629], [116218354628075/201601, 1252781991116084208780/90518849]]],
  ["Hp", [0, -1, 0, -125792010606624, -415427350830110490816],
    [[19412880, 66772174392], [67728852906/5329, 2423087106159762/389017], [366869435353/11881, 205346214100247220/1295029]]]
];}

{fd_63_38 = [
  ["ef", [1, 0, 0, -54426114516745, -149326661877655991488],
    [[-3801744259/784, 16617386054471/21952], [896449604/25, 26219493853582/125], [-9954307819/2704, 150630549616919/140608]]],
  ["eg", [1, 0, 0, -224751480208975, -1296824565825870679168],
    [[4149945852764/841, 8453928052111134922/24389]]],
  ["Hp", [0, -1, 0, -140013601817920, -435817780667752184768],
    [[19693632, 66669084344], [441210769, 9264283024500], [-3918656, 7257616200], [2918050254976/529, 4984689957571812600/12167]]]
];}

{fd_73_24 = [
  ["ef", [1, 0, 0, -94673377998924, -353919433762272635136],
    [[165941785735922/12623809, 1163275227623665811672/44852393377], [6849182848/81, 562873824313264/729], [276999061104/7225, 140527561829356872/614125]]],
  ["eg", [1, 0, 0, -153339850777260, -719732586296951884800],
    [[-42541443885113161861730/5427805672891449, 319785349496311701796684269070120/399886217417979391378707]]],
  ["Hp", [0, -1, 0, -127910198192064, 83501181854697176064],
    [[88658114, 828021224354], [30793058, 159195207710]]]
];}

{fd_88_35 = [
  ["ef", [1, 0, 0, -537960923191390, -4802565205544754983500],
    [[-34841060150/2601, 13964400757400/132651], [25919773828/9, 4172810253009322/27], [3696166969/64, 202697616686609/512]]],
  ["eg", [1, 1, 1, -1055111008889790, -13136825392429479796245],
    [[493309649203/12321, 128279863244983943/1367631], [35343087406767440245/28508296336, 210038999126499461339776928945/4813454786555584]]],
  ["Hp", [0, -1, 0, -544435463254240, 4681038068313777913600],
    [[16691472, 15618579328], [233538960, 3551739445760], [2691779600/169, 15559202910720/2197], [815573130/49, 5205476411710/343]]]
];}

{fd_99_28 = [
  ["ef", [1, 0, 0, -886286644253514, -10038599072058161134656],
    [[758166810293/13456, 538177750662874261/1560896], [384807279/4, 7132756622421/8], [2260062957/16, 104829817463691/64], [12292351281/256, 987318939754287/4096]]],
  ["eg", [1, 0, 0, -1285630732110690, -17118244345470634548000],
    [[1458435615/4, 55415570231385/8], [-4457796585631984/200364025, 61661648413522032494024/2836152773875]]],
  ["fg", [0, -1, 0, -3056260378721760, -65023932923994267595008],
    [[-660722766623/20736, 8838261973652561/2985984]]],
  ["Hp", [0, -1, 0, -1685461832548704, -10854385900968766899456],
    [[-29443120, 115094337568]]]
];}

\\ ============================================================
\\ Candidate primes: first ~70 primes above 10 (we filter to 50 valid).
\\ Skip 2,3,5,7 (likely bad/anomalous on these big-conductor curves).
\\ ============================================================

{candidate_primes = [
  11, 13, 17, 19, 23, 29, 31, 37, 41, 43,
  47, 53, 59, 61, 67, 71, 73, 79, 83, 89,
  97, 101, 103, 107, 109, 113, 127, 131, 137, 139,
  149, 151, 157, 163, 167, 173, 179, 181, 191, 193,
  197, 199, 211, 223, 227, 229, 233, 239, 241, 251,
  257, 263, 269, 271, 277, 281, 283, 293, 307, 311,
  313, 317, 331, 337, 347, 349, 353, 359, 367, 373
];}
print("Candidate prime panel size: ", #candidate_primes);

\\ ============================================================
\\ RUN
\\ ============================================================

R61 = mw_sieve_fiber_hard("(61,38)", fd_61_38, candidate_primes);
R63 = mw_sieve_fiber_hard("(63,38)", fd_63_38, candidate_primes);
R73 = mw_sieve_fiber_hard("(73,24)", fd_73_24, candidate_primes);
R88 = mw_sieve_fiber_hard("(88,35)", fd_88_35, candidate_primes);
R99 = mw_sieve_fiber_hard("(99,28)", fd_99_28, candidate_primes);

\\ ============================================================
\\ Final cross-fiber summary
\\ ============================================================

print("\n\n======================================================");
print("==     FINAL SUMMARY (50-prime hardened sieve)      ==");
print("======================================================");

{all_results = [R61, R63, R73, R88, R99];}
{for(i = 1, #all_results,
  print("Fiber ", all_results[i][1], "  sum log10(density) = ", all_results[i][3], "  total bound prod = ", all_results[i][4])
);}

print("\n=== DONE HARDENED MW SIEVE 50 ===");
quit;
