\\ Track C: Genus-2 quotient analysis for the 5 BEYOND-QC fibers.
\\
\\ H_q : y^2 = (x^2+1)(x^2+q^2)(x^2+1+q^2)  (genus 2 hyperelliptic).
\\ Set q = 2mn/(m^2-n^2). Let p = 2mn, d = m^2-n^2, w = m^2+n^2.
\\ Then 1+q^2 = w^2/d^2.  Clearing denominators (X=d*x, Y=d^3*y):
\\   Y^2 = (X^2+d^2)(X^2+p^2)(X^2+w^2)        (* integer model *)
\\ J(H_q) splits up to isogeny as E_Hp x E_Hm:
\\   E_Hp : v^2 = (u+1)(u+q^2)(u+1+q^2)        (u = x^2, v = y)
\\   E_Hm : v^2 = u(u+1)(u+q^2)(u+1+q^2)       (u = x^2, v = xy)
\\
\\ Minimal models for E_Hp, E_Hm taken from
\\ scripts/quadratic-chabauty/qc_<m>_<n>.magma which were generated by
\\ gen_magma_script.gp (ellfromeqn -> ellminimalmodel).
\\
\\ Stoll's genus-2 Chabauty applies iff rk(J(H_q)) <= g + rho_NS - 1.
\\ With g=2 and rho_NS(J(H_q)) >= 2 (because J splits over Q), bound = 3.

default(parisize, 500000000);
default(realprecision, 38);

{FIBERS = [
  ["(61,38)", 61, 38,
    [0, -1, 0, -125792010606624, -415427350830110490816],
    [[19412880, 66772174392],
     [67728852906/5329, 2423087106159762/389017],
     [366869435353/11881, 205346214100247220/1295029]],
    [1, 0, 0, -4201713691887954766021162410, 103564307677747011646913552825626935447972]
  ],
  ["(63,38)", 63, 38,
    [0, -1, 0, -140013601817920, -435817780667752184768],
    [[19693632, 66669084344],
     [441210769, 9264283024500],
     [-3918656, 7257616200],
     [2918050254976/529, 4984689957571812600/12167]],
    [1, 0, 0, -5343652737951011423545792190, 147088469266310969311366478538247305164100]
  ],
  ["(73,24)", 73, 24,
    [0, -1, 0, -127910198192064, 83501181854697176064],
    [[88658114, 828021224354],
     [30793058, 159195207710]],
    [1, 0, 0, -4296889542830417930548255320, 69513195990628448299367172717433334517312]
  ],
  ["(88,35)", 88, 35,
    [0, -1, 0, -544435463254240, 4681038068313777913600],
    [[16691472, 15618579328],
     [233538960, 3551739445760],
     [2691779600/169, 15559202910720/2197],
     [815573130/49, 5205476411710/343]],
    [1, 0, 0, -56968972021100673322719633980, -4381013374830911732760444269999712553455600]
  ],
  ["(99,28)", 99, 28,
    [0, -1, 0, -1685461832548704, -10854385900968766899456],
    [[-29443120, 115094337568]],
    [1, 0, 0, -798934373413071894873901458180, 253431216364774468941612284489290788382516752]
  ]
];}

\\ Build integer sextic polynomial in variable 'X
build_h_q(mm, nn) = {
  my(pp, dd, ww, f);
  pp = 2 * mm * nn;
  dd = mm^2 - nn^2;
  ww = mm^2 + nn^2;
  f = ('X^2 + dd^2) * ('X^2 + pp^2) * ('X^2 + ww^2);
  return([f, pp, dd, ww]);
};

\\ Count #H_q(F_p) for projective model.
\\ Affine: 2 pts for each X with f(X) a nonzero square, 1 pt for f(X)=0.
\\ Leading coefficient of f is 1 (a square), so 2 points at infinity.
count_hq_fp(f_X_poly, p) = {
  my(cnt, x_val, val);
  cnt = 0;
  for(x_val = 0, p - 1,
    val = subst(f_X_poly, 'X, x_val) % p;
    if(val == 0,
      cnt += 1,
      if(issquare(Mod(val, p)), cnt += 2)
    )
  );
  return(cnt + 2);
};

\\ Verify J(H_q) ~ E_Hp x E_Hm by matching L-factors:
\\   a_p(H_q) = (p+1) - #H_q(F_p)  must equal  a_p(E_Hp) + a_p(E_Hm)  at good p.
verify_isogeny(f_X_poly, EHp_coef, EHm_coef, primes_to_check) = {
  my(EHp, EHm, p, hq_count, lhs, rhs, all_ok, tested, tdHp, tdHm);
  EHp = ellinit(EHp_coef);
  EHm = ellinit(EHm_coef);
  tdHp = EHp.disc;
  tdHm = EHm.disc;
  print("  L-factor check (J(H_q) ?~ E_Hp x E_Hm):");
  print("    prime   #H_q(F_p)   a_p(H_q)   a_p(E_Hp)+a_p(E_Hm)   match");
  all_ok = 1; tested = 0;
  for(i = 1, #primes_to_check,
    p = primes_to_check[i];
    if(tdHp % p == 0 || tdHm % p == 0,
      print("    p=", p, "  skipped (bad reduction)");
      next
    );
    hq_count = count_hq_fp(f_X_poly, p);
    lhs = p + 1 - hq_count;
    rhs = ellap(EHp, p) + ellap(EHm, p);
    print("    p=", p, "   ", hq_count, "         ", lhs, "         ", rhs,
          "         ", if(lhs == rhs, "OK", "FAIL"));
    if(lhs != rhs, all_ok = 0);
    tested += 1
  );
  return([all_ok, tested]);
};

\\ Rank analysis: use effort=2 with alarm() guard.
\\ Returns [lo_p, hi_p, lo_m, hi_m, t_p, t_m].
rank_analysis(EHp_coef, EHm_coef) = {
  my(EHp, EHm, rp, rm, lo_p, hi_p, lo_m, hi_m, t_p, t_m);
  EHp = ellinit(EHp_coef);
  EHm = ellinit(EHm_coef);
  print("  ellrank(E_Hp, 2) running...");
  gettime();
  rp = -1;
  iferr(rp = ellrank(EHp, 2), E, print("    ellrank(E_Hp,2) errored: ", E); rp = -1);
  t_p = gettime()/1000.0;
  if(type(rp) == "t_VEC",
    lo_p = rp[1]; hi_p = rp[2];
    print("    rk(E_Hp) in [", lo_p, ",", hi_p, "]  (", t_p, "s)")
  ,
    lo_p = -1; hi_p = -1;
    print("    rk(E_Hp): UNKNOWN (", t_p, "s)")
  );
  print("  ellrank(E_Hm, 2) running...");
  gettime();
  rm = -1;
  iferr(rm = ellrank(EHm, 2), E, print("    ellrank(E_Hm,2) errored: ", E); rm = -1);
  t_m = gettime()/1000.0;
  if(type(rm) == "t_VEC",
    lo_m = rm[1]; hi_m = rm[2];
    print("    rk(E_Hm) in [", lo_m, ",", hi_m, "]  (", t_m, "s)")
  ,
    lo_m = -1; hi_m = -1;
    print("    rk(E_Hm): UNKNOWN (", t_m, "s)")
  );
  return([lo_p, hi_p, lo_m, hi_m, t_p, t_m]);
};

\\ Stoll verdict
stoll_verdict(lo_p, hi_p, lo_m, hi_m) = {
  my(lo, hi, bound);
  bound = 3;
  if(lo_p < 0 || lo_m < 0, return("unknown"));
  lo = lo_p + lo_m;
  hi = hi_p + hi_m;
  print("\n  Stoll genus-2 Chabauty (rk(J(H_q)) <= g + rho_NS - 1 = 3):");
  print("    rk(J(H_q)) in [", lo, ",", hi, "]");
  if(hi <= bound,
    print("    VERDICT: APPLIES  (rigorous: hi=", hi, " <= ", bound, ")");
    return("applies")
  );
  if(lo <= bound,
    print("    VERDICT: BORDERLINE  (lo=", lo, " <= ", bound, ", hi=", hi, " > ", bound, ")");
    return("borderline")
  );
  print("    VERDICT: FAILS  (lo=", lo, " > ", bound, ")");
  return("fails");
};

\\ Mod-p data: #H_q(F_p) for many primes
mod_p_table(f_X_poly, primes_list) = {
  my(p, cnt, ap);
  print("\n  Mod-p point counts on H_q (projective, includes 2 pts at infty):");
  print("    p     #H_q(F_p)    p+1    a_p(H_q)");
  for(i = 1, #primes_list,
    p = primes_list[i];
    cnt = count_hq_fp(f_X_poly, p);
    ap = p + 1 - cnt;
    print("    ", if(p<10," ",""), p, "    ", cnt, "        ", p+1, "    ", ap)
  )
};

\\ Direct integer-x search; also report all rational points found.
\\ The "degenerate baseline" 4 points are x=0 with y = +/-d*p*w  (4 with infty).
search_rational_points(f_X_poly, mm, nn, B) = {
  my(pp, dd, ww, fnd, x_v, val);
  pp = 2 * mm * nn;
  dd = mm^2 - nn^2;
  ww = mm^2 + nn^2;
  print("\n  Direct integer-x search on H_q(Q), |X| <= ", B, ":");
  fnd = List();
  for(x_v = -B, B,
    val = subst(f_X_poly, 'X, x_v);
    if(val < 0, next);
    if(issquare(val),
      my(y_v);
      y_v = sqrtint(val);
      listput(fnd, [x_v, y_v]);
      if(y_v == 0,
        print("    X=", x_v, "  Y=0  (Weierstrass point)")
      ,
        print("    X=", x_v, "  Y=+/-", y_v)
      )
    )
  );
  print("    integer X-points found: ", #fnd);
  return(Vec(fnd));
};

\\ =====================================================================
\\ Main loop
\\ =====================================================================
print("=============================================================");
print("Track C: Genus-2 quotient H_q analysis for 5 BEYOND-QC fibers");
print("PARI/GP ", version());
print("=============================================================");

results = Map();
t_start = getwalltime();

{for(fi = 1, #FIBERS,
  my(label, mm, nn, EHp_coef, gens_Hp, EHm_coef);
  label = FIBERS[fi][1];
  mm = FIBERS[fi][2];
  nn = FIBERS[fi][3];
  EHp_coef = FIBERS[fi][4];
  gens_Hp = FIBERS[fi][5];
  EHm_coef = FIBERS[fi][6];

  print("\n\n============================================================");
  print("Fiber ", label, "   (m,n)=(", mm, ",", nn, ")");
  print("============================================================");
  my(bb, f_X_poly, p_val, d_val, w_val, q_num, q_den, g_pd);
  bb = build_h_q(mm, nn);
  f_X_poly = bb[1];
  p_val = bb[2];
  d_val = bb[3];
  w_val = bb[4];
  q_num = p_val;
  q_den = d_val;
  g_pd = gcd(q_num, q_den);
  q_num /= g_pd;
  q_den /= g_pd;
  print("\n  q = 2mn/(m^2-n^2) = ", q_num, "/", q_den);
  print("  p = 2mn = ", p_val);
  print("  d = m^2-n^2 = ", d_val);
  print("  w = m^2+n^2 = ", w_val);
  print("\n  Integer hyperelliptic model H_q:");
  print("    Y^2 = (X^2+", d_val^2, ")(X^2+", p_val^2, ")(X^2+", w_val^2, ")");
  print("    f(X) = ", f_X_poly);
  my(disc_f);
  disc_f = poldisc(f_X_poly);
  print("\n  disc(f) = ", disc_f);
  if(disc_f != 0,
    print("  |disc(f)| factored = ", factor(abs(disc_f)))
  );

  \\ Elliptic factors
  print("\n  E_Hp minimal Weierstrass model coefs:");
  print("    ", EHp_coef);
  my(EHp_test, EHm_test, NHp, NHm, NJHq);
  EHp_test = ellinit(EHp_coef);
  EHm_test = ellinit(EHm_coef);
  NHp = ellglobalred(EHp_test)[1];
  NHm = ellglobalred(EHm_test)[1];
  NJHq = NHp * NHm;
  print("  N(E_Hp) = ", NHp);
  print("  E_Hm minimal Weierstrass model coefs:");
  print("    [a1,a2,a3] = [", EHm_coef[1], ",", EHm_coef[2], ",", EHm_coef[3], "]");
  print("    a4 = ", EHm_coef[4]);
  print("    a6 = ", EHm_coef[5]);
  print("  N(E_Hm) = ", NHm);
  print("\n  N(J(H_q)) = N(E_Hp)*N(E_Hm) = ", NJHq);

  \\ Verify isogeny
  print("\n  --- L-factor isogeny verification ---");
  my(check_primes, iso_res);
  check_primes = [13, 17, 19, 23, 29, 31, 37, 41, 43, 47];
  iso_res = verify_isogeny(f_X_poly, EHp_coef, EHm_coef, check_primes);
  if(iso_res[1],
    print("  ISOGENY VERIFIED at ", iso_res[2], " good primes")
  ,
    print("  WARNING: isogeny check FAILED at one or more primes")
  );

  \\ Rank analysis
  print("\n  --- Rank analysis (PARI ellrank effort=2) ---");
  my(rk_info, lo_p, hi_p, lo_m, hi_m, t_p, t_m);
  rk_info = rank_analysis(EHp_coef, EHm_coef);
  lo_p = rk_info[1]; hi_p = rk_info[2];
  lo_m = rk_info[3]; hi_m = rk_info[4];
  t_p = rk_info[5]; t_m = rk_info[6];

  \\ Stoll verdict
  my(verdict);
  verdict = stoll_verdict(lo_p, hi_p, lo_m, hi_m);

  \\ Mod-p table
  my(mod_p_primes);
  mod_p_primes = [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97];
  mod_p_table(f_X_poly, mod_p_primes);

  \\ Direct search to height 50000
  my(pts_found);
  pts_found = search_rational_points(f_X_poly, mm, nn, 50000);

  \\ Store summary
  mapput(results, label,
    [verdict, lo_p, hi_p, lo_m, hi_m, NHp, NHm, NJHq, #pts_found, t_p, t_m]);

  print("\n  *** Fiber ", label, " SUMMARY ***");
  print("    rk(E_Hp) in [", lo_p, ",", hi_p, "]   (t=", t_p, "s)");
  print("    rk(E_Hm) in [", lo_m, ",", hi_m, "]   (t=", t_m, "s)");
  if(lo_p >= 0 && lo_m >= 0,
    print("    rk(J(H_q)) in [", lo_p+lo_m, ",", hi_p+hi_m, "]")
  );
  print("    Stoll g=2 Chabauty verdict: ", verdict);
  print("    rational X-points (search): ", #pts_found);
);}

t_total = (getwalltime() - t_start) / 1000.0;
print("\n\n=========================================");
print("FINAL SUMMARY across all 5 BEYOND-QC fibers");
print("(total wall time: ", t_total, "s)");
print("=========================================");
{my(keys, v);
keys = ["(61,38)", "(63,38)", "(73,24)", "(88,35)", "(99,28)"];
for(k = 1, #keys,
  if(mapisdefined(results, keys[k]),
    v = mapget(results, keys[k]);
    print("  ", keys[k], ": verdict=", v[1],
          "  rk(E_Hp)=[", v[2], ",", v[3], "]",
          "  rk(E_Hm)=[", v[4], ",", v[5], "]",
          "  rk(J)=[", v[2]+v[4], ",", v[3]+v[5], "]")
  ,
    print("  ", keys[k], ": NOT COMPUTED")
  )
);}

print("\n=== DONE GENUS-2 ANALYSIS ===");
quit;
